baseurl: "/"
title: "GOCON CANADA"
canonifyurls: true
theme: "goconca"
dataDir: "Dat"

GoogleAnalytics: "UA-127047731-1"

params:
  # Conference info
  Name: "GOCON CANADA"
  Description: "Canadian Go Conference"
  Date: "May 25 â€“ 26, 2020"
  # Price: "UNKNOWN" # If your event is free, just comment this line
  Venue: "TBD"
  Address: "TBD"
  City:  "Toronto"
  State: "Ontario"
  Postcode: "M5C 2E9"
  Images: ["/img/toronto.jpg"]
  GoogleMapsKey: "AIzaSyD75cSNgqEfqbKAq-2aeBJV0gjYBw4Ys88"
  Twitter: goconcanada

  Organizers:
    - name: Mike Fridman
      homepage: https://mfridman.com
    - name: Zach Goldstein
      homepage: https://zachgoldstein.github.io/
    - name: Lubov Soltan
      homepage: https://lubovsoltan.wixsite.com/lubovsoltan
    - name: Max Gonzih
      homepage: https://gonzih.me/
    - name: Denise Yu
      homepage: https://deniseyu.io/
    # - name: Jessica Xie
    #   homepage: https://example.com/
    # - name: Spike Lindsey
    #   homepage: https://example.com/
    # - name: Johannes van der Horst
    #   homepage: https://example.com/
    # - name: Daniel Esteban
    #   homepage: https://example.com/

  Nav:
    - Url: "/#about"
      Title: "About"
    # - Url: "/#schedule"
    #   Title: "Schedule"
    # - Url: "/#sponsorship"
    #   Title: "Sponsorship"
    # - Url: "/#sponsors"
    #   Title: "Sponsors"
    # - Url: "/#tickets"
    #   Title: "Tickets"
    - Url: "/blog/"
      Title: "Blog"
    # - Url: "https://www.papercall.io/gocon-2020"
    #   Title: "Call for Papers "
    #   Icon: "fa-scroll"
    #   Target: "_blank"
    # - Url: "/speakers/"
    #   Title: "Speakers"
    # - Url: "/partners/"
    #   Title: "Partners"
    # - Url: "/#diversity-scholarship"
    #   Title: "Diversity Scholarship"
    - Url: "/contact/"
      Title: "Contact"
    - Url: "/#mailinglist"
      Title: "Subscribe"
    # - Url: "/location/"
    #   Title: "Location"
    - Url: "/code-of-conduct/"
      Title: "Code of Conduct"
    - Url: "/swag/"
      Title: "Swag"
    - Url: "https://2019.gocon.ca/"
      Title: "GOCON 2019"
